server:
    port: 8081
    servlet:
        context-path: /api
spring:
    mail:
        username: zchanglin@163.com
        password: ZLRBBNVYGEWHJGRW
        host: smtp.163.com
        port: 465
        protocol: smtp
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    ssl:
                        enable: true
    mvc:
      hiddenmethod:
        filter:
            enabled: false
    application:
        name: comment-box
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: '123456'
        url: jdbc:mysql://127.0.0.1:3306/comment-box?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: 'root'
    freemarker:
        template-loader-path: classpath:/templates
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: false
        expose-session-attributes: false
        request-context-attribute: request
        suffix: .ftl
send-mail:
    sender: zchanglin@163.com

